### ISSUE TITLE
#Stand-up team code review

### ISSUE THREAD

**Issue by JayKowski** [leonmezu1/Enumerables#3]
##The team made the following remarks:
 -Good well arranged code!
 -index can be declared inside the function instead of as a parameter
 -index should not be used as a variable name, could conflict with reserved key words
 -consider making more test cases for the "my_inject" case
 -always return to the Enumerable method if nothing is being returned by a method
 -consider not disabling the cyclomatic complexity as a good practice

**Comment by leonmezu1** [comment]
I'll look forward to making the suggested fixes.

**Comment by leonmezu1** [comment]
Just to comment I found out that index is not a reserved keyword.

**Comment by leonmezu1** [comment]
All the fixes required were made.
